# Generated by Django 2.2 on 2022-07-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20220630_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='consultant',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three')], max_length=50),
        ),
    ]
