# Generated by Django 2.2 on 2022-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20220703_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='consultant',
            field=models.CharField(choices=[('1', 'Dr. Jayesh Sharma '), ('2', 'Dr. Gaurav Gupta'), ('3', 'Dr. Ashish Mazumdar'), ('4', 'Dr. Sandip Ojha'), ('5', 'Dr. Harsha'), ('6', 'Dr. Manisha Sahu'), ('7', 'Dr Jay Kumar'), ('8', 'Dr. Kalyan Pandey'), ('9', 'Dr. Parvati Joshi'), ('10', 'Dr. Neelesh Jain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='slot',
            field=models.CharField(choices=[('1', '10:00-12:00'), ('2', '12:00-2:00'), ('3', '2:00-4:00'), ('4', '4:00-6:00')], max_length=50),
        ),
    ]
